### ISSUE TITLE
Custom Home Page

### ISSUE THREAD

**Issue by KikoPT1234** [TeamMH/minehut.xyz#6]
A better home page with a hidden navbar and a giant banner with an image and background

**Comment by KikoPT1234** [comment]
Please leave your suggestions here.

**Comment by LukasmanMHdude** [comment]
This would be epic, I can DM you the winner background I made if you would like for the minehut.xyz disc logo (oh yea, I still need to make that lol)

**Comment by KikoPT1234** [comment]
@LukasmanMHdude please do
