### ISSUE TITLE
[Feature Request] Logins

### ISSUE THREAD

**Issue by KikoPT1234** [TeamMH/minehut.xyz#8]
**Is this for the site or discord:**
Site

**Feature Suggestion:**
This feature will allow for site expansions we have planned.
Leave your suggestions here.

**Comment by LukasmanMHdude** [comment]
we probably do need logins,, ut yea, some brainstorming about what they can do would be amazing.

**Comment by Tringlle** [comment]
Writer role in the site that allows us to write tuts in the page itself

**Comment by quick007** [comment]
That would ass a ton of complexity

**Comment by Tringlle** [comment]
yep

**Comment by AdxmGG** [comment]
> Writer role in the site that allows us to write tuts in the page itself

I mean, that was the entire point of the whole login feature, but its not being developed and really has no need to be developed as tutorials can easily be written and published using the github, im sure we have a tutorial on it lol.
